### ISSUE TITLE
I can't run a sample proof score in CafeOBJ 1.5.8

### ISSUE THREAD

**Issue by Kazukiysd1023** [CafeOBJ/cafeobj#1]
Hello,

I tried to run the following sample proof score.

-- CLAIM: associativity over _+_
--        \forall i, j, k \in Nat: (i + j) + k = i + (j + k)
-- will be proven by induction on i.

-- PROOF:

open NAT+ + EQL

-- declaring three arbitrary numbers i,j and k on the sort Nat:
ops i j k : -> Nat .

-- base step:
red ((0 + j) + k) = (0 + (j + k)) .
--> should be true.

-- induction hypothesis:
eq (i + j) + k = i + (j + k) .
-- inductive step:
red ((s(i) + j) + k) = (s(i) + (j + k)) .
--> should be true.

close

-- Q.E.D.

But CafeOBJ always returns  an [ERROR] message as follows:

[Error]: module expression: "EQL" is followed by --.

Can I get how to solve this error?

Thanks in advance.

**Comment by norbusan** [comment]
Thanks for your report. Can you please send the full code (which NAT+ are you using?), either here or to info @ cafeobj . org (remove spaces)
Thanks

**Comment by Kazukiysd1023** [comment]
Thanks for your reply.
I just used a sample specification in the introductory HP for CafeOBJ.
URL:  https://cafeobj.org/intro/ja/describingspecs.html
written as follows:

mod! SIMPLE-NAT {
  [ Nat ]
  op 0 : -> Nat
  op s : Nat -> Nat
}

mod! NAT+ {
  pr(SIMPLE-NAT)
  op _+_ : Nat Nat -> Nat
  eq 0 + M:Nat = M .
  eq s (N:Nat) + M:Nat = s (N + M) .
}

This is all  what I've done, I guess...
Sorry for beginner's question.

**Comment by norbusan** [comment]
You need to write
```
op _+_ : Nat Nat -> Nat 
```
to get *infix* operators. The way you wrote it it must be used as
```
eq + ( 0, M:Nat ) = M .
```

**Comment by Kazukiysd1023** [comment]
I'm sorry for sending your the wrong information in the last message.
I actually wrote in the following way:
mod! SIMPLE-NAT {
  [ Nat ]
  op 0 : -> Nat
  op s : Nat -> Nat
}

mod! NAT+ {
  pr(SIMPLE-NAT)
  op _+_ : Nat Nat -> Nat
  eq 0 + M:Nat = M .
  eq s (N:Nat) + M:Nat = s (N + M) .
}

I defined the operator "+" as an infix operator!
But it could not work...

Thanks anyway for your kind advice.

**Comment by Kazukiysd1023** [comment]
I found out the infix definition was transformed in the wrong way after the comment button was pushed and thrown to you. 
Anyway, I wrote it in the right way as you advised me... 
CafeOBJ returns the right definition after the "show NAT+" command.

**Comment by norbusan** [comment]
Ahh, now I see the problem. You need to write
```
open NAT+ + EQL .
```
(mind the final dot). The `open` statement got several extensions and now needs a terminating `.`, which is anyway best added all the time.

Looking at the current reference manual, or the online help gives the correct syntax:
```
CafeOBJ> ? open
'open <mod_exp> .'

This command opens the module specified by the module expression
'<mod_exp>' and allows for declaration of new sorts, operators, etc.

Related: 'select', 'module expression', 'close'

CafeOBJ> 
```

Concerning the disappearing `_`: Github uses a kind of markdown where underscores have a special meaning. Best to enclose single statements in backticks: \` ... \`, and long code parts in between separate lines with triple backticks.

**Comment by norbusan** [comment]
Using the following file
```
mod! SIMPLE-NAT {
  [ Nat ]
  op 0 : -> Nat
  op s : Nat -> Nat
}

mod! NAT+ {
  pr(SIMPLE-NAT)
  op _+_ : Nat Nat -> Nat
  eq 0 + M:Nat = M .
  eq s (N:Nat) + M:Nat = s (N + M) .
}

-- CLAIM: associativity over +
-- \forall i, j, k \in Nat: (i + j) + k = i + (j + k)
-- will be proven by induction on i.

-- PROOF:

open NAT+ + EQL .

-- declaring three arbitrary numbers i,j and k on the sort Nat:
ops i j k : -> Nat .

-- base step:
red ((0 + j) + k) = (0 + (j + k)) .
--> should be true.

-- induction hypothesis:
eq (i + j) + k = i + (j + k) .
-- inductive step:
red ((s(i) + j) + k) = (s(i) + (j + k)) .
--> should be true.

close
```
and running it through CafeOBJ I get all fine output:
```
$ cafeobj -batch hoge.cafe

-- loading standard prelude
processing input : /home/norbert/hoge.cafe

-- defining module! SIMPLE-NAT
-- reading in file  : bool

processing input : /usr/share/cafeobj-1.5/lib/bool.cafe

processing input : /usr/share/cafeobj-1.5/lib/base_bool.cafe

processing input : /usr/share/cafeobj-1.5/lib/truth.cafe

-- defining module! TRUTH
-- reading in file  : truth

-- done reading in file: truth
 done.
-- defining module* BASE-BOOL
-- reading in file  : eql

processing input : /usr/share/cafeobj-1.5/lib/eql.cafe

-- defining module! EQL done.
-- done reading in file: eql
 done.
processing input : /usr/share/cafeobj-1.5/lib/sys_bool.cafe

-- defining module! BOOL done.
-- done reading in file: bool
 done.
-- defining module! NAT+ done.
-- opening module NAT+ + EQL done.
-- reduce in %NAT+ + EQL : (((0 + j) + k) = (0 + (j + k))):Bool
(true):Bool
(0.0000 sec for parse, 0.0000 sec for 3 rewrites + 11 matches)
--> should be true.
-- reduce in %NAT+ + EQL : (((s(i) + j) + k) = (s(i) + (j + k))):Bool
(true):Bool
(0.0000 sec for parse, 0.0010 sec for 5 rewrites + 32 matches)
--> should be true.[Leaving CafeOBJ]
```

**Comment by norbusan** [comment]
I updated the web pages to include the terminal `.` in all examples. Thanks for pointing this inconsistency out!!!

**Comment by Kazukiysd1023** [comment]
Thanks so much for your advice.
I got it working all right!
